# fly.toml app configuration file generated for km-slack-clone-v5-server on 2025-01-11T00:49:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'km-slack-clone-v5-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
